zh:
  contentDir: content
  defaultContentLanguageInSubdir: false
  disabled: false
  languageCode: zh-CN
  languageDirection: ltr
  languageName: 简体中文
  params:
    headTitle: 極客死亡計劃
  title: 極客死亡計劃
  weight: 1
en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  params:
    headTitle: Geek Death Project
  title: Geek Death Project
  weight: 2
