zh:
  contentDir: content
  defaultContentLanguageInSubdir: false
  disabled: false
  languageCode: zh-CN
  languageDirection: ltr
  languageName: 简体中文
  params:
    headTitle: 極客死亡計劃
    nav:
      - name: 议叙
        link: /posts/
        target: _self
      - name: 卡片
        link: /cards/
        target: _self
      - name: 书目
        link: /library/
        target: _self
      - name: 假想
        link: /fictions/
        target: _self
      - name: 自述
        link: /about/
        target: _self
    footerInternalLinks:
      - name: 林卷
        link: /linkroll/
      - name: 赞助
        link: /sponsor/
  title: 極客死亡計劃
  weight: 1
en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  params:
    headTitle: Geek Death Project
    nav:
      - name: /about
        link: /en/about/
        target: _self
      # - name: /categories
      #   link: /en/categories/
      #   target: _self
      - name: /blogroll
        link: /en/blogroll/
        target: _self
    footerInternalLinks:
      - name: blogroll
        link: /en/blogroll/
  title: Geek Death Project
  weight: 2
