zh:
  contentDir: content
  defaultContentLanguageInSubdir: false
  disabled: false
  languageCode: zh-CN
  languageDirection: ltr
  languageName: 简体中文
  params:
    headTitle: 極客死亡計劃
    nav:
      - name: 议叙
        link: /posts/
        target: _self
      - name: 卡片
        link: /cards/
        target: _self
      - name: 书目
        link: /library/
        target: _self
      - name: 假想
        link: /fictions/
        target: _self
      - name: 自述
        link: /about/
        target: _self
    series:
      - name: 人类恶疾
        link: /categories/人类恶疾/
        cover: https://image.guhub.cn/uPic/2025/01/%E4%BA%BA%E7%B1%BB%E6%81%B6%E7%96%BE.jpeg
        description: 尝试以非专业的病理视角分析人类行为
      - name: 塔罗牌漫谈
        link: /categories/塔罗牌漫谈/
        cover: https://image.guhub.cn/uPic/2025/01/%E5%A1%94%E7%BD%97%E7%89%8C%E6%BC%AB%E8%B0%88%E5%B0%81%E9%9D%A2.jpeg
        description: 随便聊聊牌意
      - name: 稻草人周刊
        link: /categories/稻草人周刊/
        cover: https://image.guhub.cn/uPic/2025/01/%E7%A8%BB%E8%8D%89%E4%BA%BA%E5%91%A8%E5%88%8A.jpeg
        description: 个人化的信息整合，每周一更新
  title: 極客死亡計劃
  weight: 1
en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  params:
    headTitle: Geek Death Project
    nav:
      - name: /about
        link: /en/about/
        target: _self
      # - name: /categories
      #   link: /en/categories/
      #   target: _self
      - name: /blogroll
        link: /en/blogroll/
        target: _self
  title: Geek Death Project
  weight: 2
