goldmark:
  renderer:
    unsafe: true
  parser:
    attribute:
      block: true
      title: true
    wrapStandAloneImageWithinParagraph: false
  extensions:
    extras:
      mark:
        enable: true
highlight:
  guessSyntax: true
  noClasses: true
  style: evergarden
  tabWidth: 2
tableOfContents:
  startLevel: 2
  endLevel: 3
