baseURL = 'https://geedea.pro/'
languageCode = 'zh-cn'
title = '極客死亡計劃'
theme = "yinyang"
timeZone = "Asia/Shanghai"
hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[params]
headTitle = "極客死亡計劃"
mainSections = ["posts"]
favicon = "/favicon.png"

[[params.socials]]
name = "关于"
link = "/about"
target = "_self"

[[params.socials]]
name = "链接"
link = "/links"
target = "_self"

[[params.socials]]
name = "RSS"
link = "/posts/index.xml"
target = "_blank"

[services]
  [services.rss]
    limit = 10

